# PostgreSQL Database Connection

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#GCP Cloud SQL properties

# Core GCP Settings
spring.cloud.gcp.project-id=cybernetic-pact-417810

# Cloud SQL Configuration
spring.cloud.gcp.sql.instance-connection-name=cybernetic-pact-417810:asia-south1:sree-wallet-db-dev
spring.cloud.gcp.sql.database-name=wallet-app

# Database Credentials
spring.datasource.username=sree-demo-db-user
spring.datasource.password=2Sna2n&N"M}uQ$}+
#Git demo
#add New properties
#Supabase properties
#spring.datasource.url=jdbc:postgresql://db.qnjufrshzrbmlxgwpiqq.supabase.co:5432/postgres?user=postgres&password=K*t2_cxeQeskHP%40
#spring.datasource.username=postgres
#spring.datasource.password=K*t2_cxeQeskHP%40
spring.datasource.driver-class-name=org.postgresql.Driver
# Sets the PostgreSQL dialect for Hibernate

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# H2 setup
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:./data/demo
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.h2.console.enabled=true
# hibernate setup
#Testing
#spring.jpa.hibernate.ddl-auto = create-drop
#Developement
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto = validate
#spring.jpa.hibernate.ddl-auto = none
#spring.jpa.open-in-view = false
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

#GraphQl
#spring.graphql.graphiql.enabled=true